version: 0.0
os: linux
files:
  - source: /app
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 120
      runas: root  
  AfterInstall:
    - location: scripts/after_install
      timeout: 120
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 120
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 120
      runas: root

