#!/bin/bash

sudo cp .env.example .env
sudo chown -R $WEB_USER:$WEB_USER .
sudo chmod -R u+x .
sudo chmod -R g+w storage
sudo chmod -R 777 storage
sudo chmod -R 777 storage/*
sudo chmod -R g+w bootstrap
sudo chmod -R 777 bootstrap
sudo chown -R $WEB_USER_DATA:$WEB_USER_DATA storage/*
sudo mkdir vendor
sudo chmod -R 777 vendor

sudo composer install 

# sudo composer update
php artisan key:generate
php artisan migrate
sudo systemctl restart apache2