#!/bin/bash

export PHP_VERSION ="php8.2"

sudo apt update && apt upgrade

# remove php
# sudo add-apt-repository ppa:ondrej/php -r -y
# sudo apt remove --autoremove php* libapache2-mod-php* php*

sudo apt install -y apache2


# sudo apt-get install software-properties-common
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install php8.2
sudo apt-get install -y php8.2-mysql php8.2-zip 
sudo apt-get install -y php8.2-gd php8.2-mbstring php8.2-xml php8.2-gd
# sudo apt install curl
sudo apt-get install -y php8.2-curl
# sudo apt install -y php8.3 

php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('sha384', 'composer-setup.php') === 'dac665fdc30fdd8ec78b38b9800061b4150413ff2e3b6f88543c636f7cd84f6db9189d43a81e5503cda447da73c7e5b6') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"

sudo mv composer.phar /usr/local/bin/composer




