#!/bin/bash

export PHP_VERSION ="php8.2"

sudo apt install -y apache2 php8.2 composer
sudo apt-get install -y $PHP_VERSION-mysql $PHP_VERSION-zip $PHP_VERSION-gd $PHP_VERSION-mbstring $PHP_VERSION-curl $PHP_VERSION-xml $PHP_VERSION-gd

