#!/bin/bash
cd /var/www/html
sudo composer install 
# sudo composer update
php artisan key:generate
php artisan migrate

# sudo systemctl apache2 restart
sudo /etc/init.d/apache2 restart

php artisan breeze:install
php artisan migrate
npm install
npm run dev