#!/bin/bash
export CONFIG_FILE_NAME="app.conf"

export WEBSITE_DIR="/var/www/html"

export SERVER_ADMIN="salestransportes@gmail.com"

export WEB_USER="root"

export WEB_USER_DATA="www-data"

export SERVER_NAME=$(wget -qO- ifconfig.me/ip)

export SERVER_ALIAS=$(wget -qO- ifconfig.me/ip)

sudo systemctl start apache2

cd /etc/apache2/sites-available

sudo cp 000-default.conf app.conf

echo "<VirtualHost *:80>" >> $CONFIG_FILE_NAME
echo "  ServerAdmin $SERVER_ADMIN" >> $CONFIG_FILE_NAME
echo "  ServerName $SERVER_NAME" >> $CONFIG_FILE_NAME
echo "  ServerAlias $SERVER_ALIAS" >> $CONFIG_FILE_NAME
echo "  DocumentRoot $WEBSITE_DIR/public" >> $CONFIG_FILE_NAME
echo "  <Directory $WEBSITE_DIR>" >> $CONFIG_FILE_NAME
echo "    Require all granted" >> $CONFIG_FILE_NAME
echo "    AllowOverride All" >> $CONFIG_FILE_NAME
echo "    Options Indexes Multiviews FollowSymLinks" >> $CONFIG_FILE_NAME
echo "  </Directory>" >> $CONFIG_FILE_NAME
echo "</VirtualHost>" >> $CONFIG_FILE_NAME

echo "  ErrorLog ${APACHE_LOG_DIR}/error.log" >> $CONFIG_FILE_NAME
echo "  CustomLog ${APACHE_LOG_DIR}/access.log combined" >> $CONFIG_FILE_NAME

sudo a2dissite 000-default.conf
sudo a2ensite app.conf
# sudo systemctl restart apache2
sudo a2enmod rewrite
# sudo /etc/init.d/apache2 restart
sudo systemctl restart apache2
cd $WEBSITE_DIR
sudo cp .env.example .env
sudo chown -R $WEB_USER:$WEB_USER .
sudo chmod -R u+x .
sudo chmod -R g+w storage
sudo chmod -R 777 storage
sudo chmod -R g+w bootstrap
sudo chmod -R 777 bootstrap
sudo chown -R $WEB_USER_DATA:$WEB_USER_DATA storage/*
sudo mkdir vendor
sudo chmod -R 777 vendor

sudo composer install 

# sudo composer update
php artisan key:generate
php artisan migrate
sudo systemctl restart apache2
# sudo /etc/init.d/apache2 restart